### ISSUE TITLE
navigation styling

### ISSUE THREAD

**Issue by DanielssonThomas** [DanielssonThomas/space-tracker#1]
## Task
It would be great to have a transition for the navigation. Something like a toggle for a slide in to view transition. The 

### Requirements
- Keep the design as  [accessibility friendly](https://www.w3.org/WAI/tips/designing/) as possible.
- Don't stray too far from the current design. (*In this case avoid strong contrasting colors or over the top details, as the current styling is simplistic*)

### Files effected
The navigation is going to be available on all pages, so the `components/global` should be the only folder changed in this task. As to how you implement the changes, it is entirely up to you 😄

**Comment by iamshobhraj** [comment]
can you assign this to me. i am new to open source contributions but i have worked on next js projects

**Comment by DanielssonThomas** [comment]
> can you assign this to me. i am new to open source contributions but i have worked on next js projects

Absolutely! Thank you :)

**Comment by DanielssonThomas** [comment]
@iamshobhraj Any update on this?

**Comment by iamshobhraj** [comment]
> @iamshobhraj Any update on this?

i raised a PR [#2 ](https://github.com/DanielssonThomas/space-tracker/pull/2#issue-1931480613)
